Fix uv4l configuration file construction
resin-io-playground/resin-cam pull request #7
Opened 2018-07-25 10:09 UTC by mbalamat

2018-07-25 11:04 UTC, richbayliss commented on app/set_option.sh
> +    cat $3 | grep "^$1" > /dev/null && \
Not sure what this is doing? it looks like it is searching for the option, but it throws it away in either case. If it is not required then I would say remove it.

2018-07-25 11:04 UTC, richbayliss commented on app/set_option.sh
> +        sed -i "s+^$1.*+$1 = $2+g" $3 || \
Error case; given the 2 options `device_name_full` and `device_name`...
- `$1`  = `device_name_full` > gets appended to file `$3`
- `$1` = `device_name` > is found by `sed` commmand and substituted
- file `$3` is incorrect

Possible Solution:
- change the regex in your `sed` substitute for (from memory here) `^$1\s*\=.*$`
  - `(SOL)(value of $1)(0 or more whitespace)(= char)(0 or more characters of any type)(EOL)`

2018-07-25 11:12 UTC, mbalamat commented on app/set_option.sh
> +    cat $3 | grep "^$1" > /dev/null && \
Yeah, it throws it away because I am interested in the return value of the command. The command essentially says: try to find the env var in the conf file, if you find it run sed on it, else append it to the conf file.

2018-07-25 11:13 UTC, zrzka commented on app/set_option.sh
> +    cat $3 | grep "^$1" > /dev/null && \
Also it would be nice if more comments can be included. Imagine you're going to look at this few weeks later, will you know what it does / what it should do for sure?

2018-07-25 11:22 UTC, zrzka commented
Also I'd recommend to read [Resin Commit Guidelines Proposal](https://docs.google.com/document/d/1Lip9ZwMx5K-9k6-QFCeAu3tfDwR431fGtmTwq8bnC2o). It's just a proposal, but many projects already do obey these rules. Especially when you said:

> okay I think I've fixed the issue for this one.

Something like ...

```text
core: Fix uv4l configuration file construction

Connects-to: #123
Change-type: patch
Signed-off-by: Name <email@resin.io>
```

... can do the trick. Also check [resin-commit-lint](https://github.com/resin-io/resin-commit-lint) project for more details. It's good to learn these things, so, you can do it naturally when you commit to any project outside of playground with version bot involved, etc.

2018-07-25 15:37 UTC, nistath commented
What is the issue here in the first place?

2018-07-26 07:22 UTC, mbalamat commented
Hi @nistath I am trying to fix #5 and #6

2018-07-26 10:50 UTC, nistath commented
@mbalamat I am fairly certain those are issues with UV4L, although I haven't had a chance to reproduce. The current code works fine w.r.t. editing the configuration file.

2018-07-26 13:15 UTC, mbalamat commented
@nistath I've reproduced it, and I think this PR fixes it. I am actually stepping on your footsteps, so thanks for your contribution!

2018-07-27 12:02 UTC, zrzka requested changes
Couple of nitpicks :)

2018-07-27 12:02 UTC, zrzka commented on README.md
> +You can also configure UV4l on the fly, using `http://<raspberrypi>/panel`.
Remove comma?

2018-07-27 12:02 UTC, zrzka commented on README.md
> +Where `<raspberrypi>` the IP address of your Pi or the Public URL, both of them can be found in your resin.io account's Dashboard.
Missing _is_ (Where `<raspberrypi>` is ...)?

2018-07-27 12:02 UTC, zrzka commented on app/set_option.sh
> +    # Try to find the var ($1) in the file ($3), if grep is successful run sed on it, else append the var to the file.
* Personally, I don't like abbreviations (even simple ones like _var_)
* I also miss what's `$2`
* _run sed on it_ says nothing, I see that you're running _sed on it_

Something like this should do the trick:

```bash
# Try to replace variable ($1) value with the new one ($2) in the file ($3).
# Append variable to the file if it doesn't exist. Create file with the
# variable if the file doesn't exist.
```

This is just a simple thing. My point is that we should use human language and not semi human computer language like _if grep is successful_.

2018-07-27 12:02 UTC, zrzka commented on app/set_option.sh
>  # Look for pre-existing option. If not found, create it.
This isn't valid statement. What it does if found?

2018-07-27 12:02 UTC, zrzka commented on app/set_option.sh
> +    cat $3 | grep "^$1\s*=.*$" > /dev/null && \
* `grep` has `-q` option to disable matches printing (no need `> /dev/null`)
* `grep` can accept file as an argument (no need `cat`)
* What if file ($3) contains a space? It wont work.

What about?

```bash
#!/bin/bash

# Try to replace variable ($1) value with the new one ($2) in the file ($3).
# Append variable to the file if it doesn't exist. Create file with the
# variable set if the file doesn't exist.
set_option() {
    if [[ -z $1 || -z $2 || -z $3 ]]; then return; fi

    [[ -f "$3" ]] \
        && grep -q "^$1\s*=.*$" "$3" && sed -i "s+^$1\s*=.*$+$1 = $2+g" "$3" \
        || echo "$1 = $2" >> "$3"
}
```

2018-07-27 16:25 UTC, zrzka approved these changes

2018-07-31 10:13 UTC, merged

2018-07-31 10:14 UTC, zrzka commented
Merged based on @mbalamat request:

> Good morning Robert! Would you mind checking the PR and merge it if everything is ok?